IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PatternCavityMaster' AND COLUMN_NAME = 'MaterialGrade')
BEGIN
    ALTER TABLE PatternCavityMaster ADD MaterialGrade NVARCHAR(255);
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PatternMaster' AND COLUMN_NAME = 'No_Of_Cavities')
BEGIN
    ALTER TABLE PatternMaster DROP COLUMN No_Of_Cavities;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PatternMaster' AND COLUMN_NAME = 'Casting_Material_Grade')
BEGIN
    ALTER TABLE PatternMaster DROP COLUMN Casting_Material_Grade;
END
