
export const AVAILABLE_PAGES = [
    { id: 'homepage', label: 'Homepage', path: '/', isLocked: true },
    { id: 'sales-dashboard', label: 'Sales Dashboard', path: '/sales-dashboard' },
    { id: 'finance-dashboard', label: 'Finance Dashboard', path: '/finance-dashboard' },
    { id: 'ar-ap-dashboard', label: 'AR Dashboard', path: '/ar-ap-dashboard' },
    { id: 'production-dashboard', label: 'Production Dashboard', path: '/production-dashboard' },
    { id: 'pattern-master', label: 'Pattern Master', path: '/pattern-master' },
    { id: 'pattern-process-card', label: 'Pattern-Process Card', path: '/pattern-master', isSubTab: true, parent: 'pattern-master' },
    { id: 'pattern-return-history', label: 'Pattern Return History', path: '/pattern-master', isSubTab: true, parent: 'pattern-master' },
    { id: 'planning-master', label: 'Planning', path: '/planning-master' },
    { id: 'planning-schedule', label: 'Planning Schedule Qty', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-entry', label: 'Planning Entry', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-sleeve', label: 'Sleeve Requirement', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-sleeve-indent', label: 'Sleeve Indent', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'lab-master', label: 'Lab Master', path: '/lab-master' },
    { id: 'drawing-master', label: 'Drawing Master', path: '/lab-master', isSubTab: true, parent: 'lab-master' },
    { id: 'drawing-details', label: 'Drawing Details', path: '/lab-master', isSubTab: true, parent: 'lab-master' },
    { id: 'melting', label: 'Melting', path: '/melting' },
    { id: 'quality-lab', label: 'Quality & Lab', path: '/quality-lab' },
    { id: 'quality-lab-physical', label: 'Physical Properties', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-micro', label: 'Microstructure & Hardness', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-sand', label: 'Sand Properties', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-chemistry', label: 'Chemistry (Spectro)', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-mould', label: 'Mould Hardness', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'it-management', label: 'IT Management', path: '/it-management' },
    { id: 'database-explorer', label: 'Database Explorer', path: '/database-explorer' },
    { id: 'marketing', label: 'Marketing', path: '/marketing' },
];
