
export const AVAILABLE_PAGES = [
    { id: 'homepage', label: 'Homepage', path: '/', isLocked: true },
    { id: 'sales-dashboard', label: 'Sales Dashboard', path: '/sales-dashboard' },
    { id: 'finance-dashboard', label: 'Finance Dashboard', path: '/finance-dashboard' },
    { id: 'ar-ap-dashboard', label: 'AR Dashboard', path: '/ar-ap-dashboard' },
    { id: 'production-dashboard', label: 'Production Dashboard', path: '/production-dashboard' },
    { id: 'rejection-dashboard', label: 'Rejection Dashboard', path: '/rejection-dashboard' },
    { id: 'daily-dashboard', label: 'Day-wise Dashboard', path: '/daily-dashboard' },
    { id: 'daily-dashboard-sales', label: 'Sales', path: '/daily-dashboard', isSubTab: true, parent: 'daily-dashboard' },
    { id: 'daily-dashboard-production', label: 'Production', path: '/daily-dashboard', isSubTab: true, parent: 'daily-dashboard' },
    { id: 'pattern-master', label: 'Pattern Master', path: '/pattern-master' },
    { id: 'pattern-process-card', label: 'Pattern-Process Card', path: '/pattern-master', isSubTab: true, parent: 'pattern-master' },
    { id: 'pattern-return-history', label: 'Pattern Return History', path: '/pattern-master', isSubTab: true, parent: 'pattern-master' },
    { id: 'planning-master', label: 'Planning', path: '/planning-master' },
    { id: 'planning-schedule', label: 'Planning Schedule Qty', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-entry', label: 'Planning Entry', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-sleeve', label: 'Sleeve Requirement', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'planning-sleeve-indent', label: 'Sleeve Indent', path: '/planning-master', isSubTab: true, parent: 'planning-master' },
    { id: 'lab-master', label: 'Lab Master', path: '/lab-master' },
    { id: 'drawing-master', label: 'Drawing Master', path: '/lab-master', isSubTab: true, parent: 'lab-master' },
    { id: 'drawing-details', label: 'Drawing Details', path: '/lab-master', isSubTab: true, parent: 'lab-master' },
    { id: 'melting', label: 'Melting', path: '/melting' },
    { id: 'quality-lab', label: 'Quality & Lab', path: '/quality-lab' },
    { id: 'quality-lab-physical', label: 'Physical Properties', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-micro', label: 'Microstructure & Hardness', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-sand', label: 'Sand Properties', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-chemistry', label: 'Chemistry (Spectro)', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-mould', label: 'Mould Hardness', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-lab-reports', label: 'Reports', path: '/quality-lab', isSubTab: true, parent: 'quality-lab' },
    { id: 'quality-management-system', label: 'Quality Management System', path: '/quality-management-system' },
    { id: 'qms-spc', label: 'Statistical Process Control', path: '/quality-management-system/spc', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-analysis', label: 'Analysis Results', path: '/quality-management-system/analysis', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-foundry-readings', label: 'Foundry Readings', path: '/quality-management-system/foundry-readings', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing', label: 'Sand Testing Dashboard', path: '/quality-management-system/sand-testing', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-green', label: 'Green Compression', path: '/quality-management-system/sand-testing/green-compression', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-moisture', label: 'Moisture Content', path: '/quality-management-system/sand-testing/moisture', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-compactibility', label: 'Compactibility', path: '/quality-management-system/sand-testing/compactibility', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-permeability', label: 'Permeability', path: '/quality-management-system/sand-testing/permeability', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-comparison', label: 'Comparison', path: '/quality-management-system/sand-testing/comparison', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-new-reading', label: 'New Reading', path: '/quality-management-system/sand-testing/new-reading', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-import', label: 'Import CSV', path: '/quality-management-system/sand-testing/import-csv', isSubTab: true, parent: 'quality-management-system' },
    { id: 'qms-sand-testing-analysis', label: 'Analysis Results (Sand)', path: '/quality-management-system/sand-testing/analysis-results', isSubTab: true, parent: 'quality-management-system' },
    { id: 'it-management', label: 'IT Management', path: '/it-management' },
    { id: 'database-explorer', label: 'Database Explorer', path: '/database-explorer' },
    { id: 'marketing', label: 'Marketing', path: '/marketing' },
    { id: 'marketing-rfq', label: 'RFQ', path: '/marketing', isSubTab: true, parent: 'marketing' },
    { id: 'marketing-laboratory', label: 'Laboratory', path: '/marketing', isSubTab: true, parent: 'marketing' },
    { id: 'marketing-patternshop', label: 'Patternshop / Development', path: '/marketing', isSubTab: true, parent: 'marketing' },
    { id: 'marketing-rfq-master', label: 'RFQ Master', path: '/marketing', isSubTab: true, parent: 'marketing' },
];
